### PR TITLE
Add support for additionalProperties with a schema.

### PR DESCRIPTION
**Pull request by adamgreig**
When an object has additionalProperties specified as an object rather than a
boolean, consider the object to be the schema for any other properties in the
object instance and render it as appropriate, passing the additionalProperties
schema on to later levels.

This works fine on all the data I tried it with, correctly rendering complex hierarchies where the additionalProperties are objects that have further levels of schema. For example:

http://habitat.habhub.org/onde/samples/app.html#?schema_url=schemas/flight.json&data_url=data/flight.json

### CODE REVIEW

**Comment by huyl** [comment]
@adamgreig Can you post your flight.json schema again?  Get a 404 on that URL at habhub.org

**Comment by adamgreig** [comment]
@huyl done (though maybe also check out http://habitat.habhub.org/jse/#schemas/flight.json which is a tool I wrote just to view jsonschema docs without editing, at https://github.com/ukhas/jsonschema-explorer )

**Comment by huyl** [comment]
@adamgreig Thanks for all that.  Quite useful

**Comment by huyl** [comment]
@adamgreig Hmmm, I tried the additionalProperties where the value is a schema object using your http://habitat.habhub.org/onde/samples/app.html#?schema_url=schemas/payload_telemetry.json and I get this error
Uncaught TypeError: Cannot call method 'addClass' of null onde.js
in or around line 233

Any idea how to fix that?

**Pull request merged**
