### PR TITLE
Fix unsupported field type detection on objects

### PR DESCRIPTION
**Pull request by jbpros**
This properly detects unsupported field types on objects.

### CODE REVIEW

**Comment by huyl** [comment]
I think this commit breaks the code

**Comment by jbpros** [comment]
@huyl could you be more specific?

**Comment by huyl** [comment]
When I try this change with `onde/samples/schemas/jquery-package.json`

I get the following JS errors:

```
Invalid field info type: object onde.js:680
Invalid field info type: array onde.js:680
Invalid field info type: object onde.js:680
Invalid field info type: array onde.js:680
Invalid field info type: array onde.js:680
Invalid field info type: array onde.js:680
```

**Comment by jbpros** [comment]
@huyl you're right, this is all wrong. Withdrawing pull request.

**Pull request closed without merging**
